DROP TABLE IF EXISTS MEMBRE;
DROP TABLE IF EXISTS LOGER; 
DROP TABLE IF EXISTS PARTICIPE;
DROP TABLE IF EXISTS HEBERGEMENT;
DROP TABLE IF EXISTS SINSCRIT;
DROP TABLE IF EXISTS EVENEMENT;
DROP TABLE IF EXISTS TYPES;
DROP TABLE IF EXISTS RESSEMBLE;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS BILLET;
DROP TABLE IF EXISTS AIME;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS GROUPE;
DROP TABLE IF EXISTS STYLE;

